version: '3.4'
services:
  keycloak:
    image: jboss/keycloak:3.4.0.Final
    command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING", "-Djboss.socket.binding.port-offset=1000"]
    restart: on-failure
    volumes:
      - ./config/keycloak:/opt/jboss/keycloak/realm-config
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - "9080:9080"
      - "9443:9443"
  zookeeper:
    image: wurstmeister/zookeeper
    restart: on-failure
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-conf:/opt/zookeeper-3.4.9/conf
      - zookeeper-data:/opt/zookeeper-3.4.9/data
  kafka:
    image: wurstmeister/kafka:0.10.1.1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ADVERTISED_PORT:  ${KAFKA_ADVERTISED_PORT}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: courses:1:1,chapters:1:1,pages:1:1
    restart: on-failure
    ports:
      - "${KAFKA_ADVERTISED_PORT}:${KAFKA_ADVERTISED_PORT}"
    depends_on:
      - zookeeper
    volumes:
      - kafka:/kafka

volumes:
  kafka:
  zookeeper-conf:
  zookeeper-data:
