version: '3.4'
services:
  keycloak:
    image: jboss/keycloak-mysql:3.4.3.Final
    command: ["-b", "0.0.0.0", "-Djboss.socket.binding.port-offset=1000"]
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      MYSQL_PORT_3306_TCP_ADDR: keycloak-db
      MYSQL_PORT_3306_TCP_PORT: 3306
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    ports:
      - "9080:9080"
      - "9443:9443"
    depends_on:
      - keycloak-db
  keycloak-db:
    image: mariadb:10.1
    volumes:
      - keycloak-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak

volumes:
  keycloak-db:
