version: '3.4'
services:
  keycloak:
    image: jboss/keycloak-mysql:3.4.3.Final
    command: ["-b", "0.0.0.0", "-Djboss.socket.binding.port-offset=1000"]
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      MYSQL_PORT_3306_TCP_ADDR: keycloak-db
      MYSQL_PORT_3306_TCP_PORT: 3306
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    ports:
      - "9080:9080"
      - "9443:9443"
    depends_on:
      - zookeeper
  keycloak-db:
    image: mysql
    volumes:
      - keycloak-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - zookeeper-conf:/opt/zookeeper-3.4.9/conf
      - zookeeper-data:/opt/zookeeper-3.4.9/data
  kafka:
    image: wurstmeister/kafka:0.10.1.1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ADVERTISED_PORT:  ${KAFKA_ADVERTISED_PORT}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: courses:1:1,chapters:1:1,pages:1:1
    ports:
      - "${KAFKA_ADVERTISED_PORT}:${KAFKA_ADVERTISED_PORT}"
    depends_on:
      - zookeeper
    volumes:
      - kafka:/kafka

volumes:
  kafka:
  zookeeper-conf:
  zookeeper-data:
  keycloak-db:
